// <auto-generated />
using System;
using ExchangeSync.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExchangeSync.Model.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20190902070133_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExchangeSync.Model.UserConnect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("HashPassword")
                        .HasMaxLength(256);

                    b.Property<string>("IdCard")
                        .HasMaxLength(64);

                    b.Property<string>("Name")
                        .HasMaxLength(32);

                    b.Property<string>("Number")
                        .HasMaxLength(32);

                    b.Property<string>("OpenId")
                        .HasMaxLength(256);

                    b.Property<string>("UserName")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("UserConnects");
                });

            modelBuilder.Entity("ExchangeSync.Model.UserWeChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OpenId");

                    b.Property<string>("SsoId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserWeChats");
                });
#pragma warning restore 612, 618
        }
    }
}
